### ISSUE TITLE
下载的问题

### ISSUE THREAD

**Issue by liguangze** [Taonce/WanKotlin#1]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/10549682/58945388-5caab600-87b6-11e9-8450-c916353a1d0e.png">

我为什么一直卡在这一步了，

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/10549682/58945466-7d730b80-87b6-11e9-9635-e494556118b3.png">

插件也下载了，但是就是运行不了你的项目，
我自己新建一个就没有问题

就是自己新建的ext.kotlin_version = '1.2.61'是这个版本

刚刚入手kotlin ,

**Comment by Taonce** [comment]
1.3.21版本的Kotlin下载不下来么？

**Comment by liguangze** [comment]
可以了，可能是下载的原因，感谢开源
